### ISSUE TITLE
need to manually write album title on web scrobbler for youtube music

### ISSUE THREAD

**Issue by fakeoliviahye** [web-scrobbler/web-scrobbler#2843]
**Describe the bug**
On YouTube Music, when I try scrobbling a song, I open the track information up, and there is no album name there... I am unsure why this is, and is there a way I can fix it???

**Expected behavior**
It should pull up the album name when you listen to the song.

**Screenshots**
<img width="359" alt="Screen Shot 2021-04-24 at 2 34 47 PM" src="https://user-images.githubusercontent.com/83136766/115969302-4624b980-a50a-11eb-8719-69d314765a74.png">

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Chrome
-   Extension version: unsure

**Additional context**

**Comment by yayuyokitano** [comment]
This is caused by an update to youtube music behind the scenes.
Should be fixed by #2834

**Comment by fakeoliviahye** [comment]
oh thanks

**Comment by peepincreepin** [comment]
@yayuyokitano There seems to be an additional issue caused by the change to youtube music behind the scenes. Web Scrobbler is putting in the wrong album name for lots of songs. For example, I played the track _Love Is Wicked_ by the artist Brick & Lace, from the album **Love Is Wicked**, but WS puts the album as **Bratz: The Movie**. Screenshot here: https://imgur.com/6EAQgp9

OS: ChromeOS
Browser: Chrome

**Comment by peepincreepin** [comment]
> This is caused by an update to youtube music behind the scenes.
> Should be fixed by #2834

I'm still getting some missing album names. E.g. [Screenshot](https://imgur.com/2xIw0N9) taken 2021-04-25 04.01.13 (British Summer Time)
