### ISSUE TITLE
Audacy has redesigned its site

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#3320]
A few weeks ago, Audacy changed the design of its site. The connector should be updated.

https://www.audacy.com/?action=AUTOPLAY_FULL&actionContentId=101-545

**Comment by hornbuckle** [comment]
The issue is that Audacy has at least 3 different types of players on their site, and it will take some effort to update the selector to support all of them.

If you go to the main station page, such as https://www.audacy.com/kearth101 from your example, the connector works fine.

**Comment by rcozmyer** [comment]
It looks like stations no longer stream directly from https://www.audacy.com/kearth101, they redirect you to https://www.audacy.com/stations/kearth101 via the player at the bottom of the page.

**Comment by 4fthawaiian** [comment]
this seems to not work still?

**Comment by hornbuckle** [comment]
It was working when that fix was submitted, but something got changed during one of the automated V3 updates that broke the syntax in the connector.

Unfortunately, I haven't been able to get the V3 project to work locally, so I haven't been able to test/submit any edits.

**Comment by 4fthawaiian** [comment]
> Unfortunately, I haven't been able to get the V3 project to work locally, so I haven't been able to test/submit any edits.

not sure what "v3 project" means, sorry - I'll try to get the dev copy of the extension running locally to see if I can contribute. Should this be reopened, or do we need a new issue?

**Comment by hornbuckle** [comment]
Since this extension went through a major overhaul from V2 to V3, it hasn't worked locally for me, so I haven't been able to contribute. 😔

I believe the connector should still work without any major changes, as the site hasn't been redesigned since #3595 was submitted, if the syntax is corrected on lines 11–13, 21–23, 31–33, and 40–42: https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/audacy.ts

If you are able to fix it, it doesn't seem necessary to create a new issue; you can just reference this one when submitting a pull request.

**Comment by 4fthawaiian** [comment]
i have the extension running from a local build now, but it still doesn't work for audacy :/ 

I'll see what I can find out from the error console

**Comment by 4fthawaiian** [comment]
![image](https://github.com/web-scrobbler/web-scrobbler/assets/1187264/cea949e6-a345-4180-a861-72e789eb7b6b)

i get this in the error console, and the popup displays "this website is not supported" - I can try and get more output by looking at the bits you called previously in audacy.ts
