### ISSUE TITLE
Re-add connector for Bandcamp

### ISSUE THREAD

**Issue by McFaceman** [web-scrobbler/web-scrobbler#4833]
Tracks on Bandcamp were previously detected on Safari but are not now and instead show the WS icon for the extension. I can’t find the exact time this change happened, but I’m sure it was after July 3rd, 2:20am EST.

**Comment by McFaceman** [comment]
i am using mobile safari
i am currently on v3.6.2

**Comment by inverse** [comment]
There was support for Mobile Bandcamp added in v3.8.0 -  https://github.com/web-scrobbler/web-scrobbler/releases/tag/v3.8.0

Unfortunately the maintainer who can push this has been super busy recently.

**Comment by inverse** [comment]
@McFaceman is this resolved now that v3.9.0 is available in Safari?

**Comment by McFaceman** [comment]
no

**Comment by swimtrunks** [comment]
@McFaceman ,is this ready to be closed?

im taking a look at the bandcamp connector but scrobbling from bandcamp seems to be functioning on mobile safari. there are some players that might not be supported as of the new UI implementation on the site but at the very least album pages and song pages are working for me.

**Comment by rob9315** [comment]
mobile UI should be supported by the current extension version. this issue is now quite old and anyone still experiencing this probably does so as a symptom of #5318
